# Atom feed
# Add "ATOM" to the Page Kinds under [outputs] (in your site config) for which
# you want to enable Atom feeds.
# Example:
#   [outputs]
#     home = ["HTML", "ATOM"]
# https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false
