*This is not a standalone theme. This is a Hugo theme component.*

To enable ATOM feeds for your site:

1. Clone this repo to ~<your-site-dir>/themes/hugo-atom-feed~ directory.
2. Add these your site's ~config.toml~:
   - Add "hugo-atom-feed" as the *left-most element* of the ~theme~
     list variable. For example:
     #+begin_src toml
     theme = ["hugo-atom-feed", "my-theme"]
     #+end_src
   - Add "ATOM" to all the Page Kinds for which you want to create
     ATOM feeds:
     #+begin_src toml
     [outputs]
       # <domain>/atom.xml
       home = ["HTML", "RSS", "ATOM"]     # default = ["HTML", "RSS"]
       # <domain>/posts/atom.xml
       section = ["HTML", "RSS", "ATOM"]  # default = ["HTML", "RSS"]
       # <domain>/tags/mytag/atom.xml, <domain>/categories/mycat/atom.xml
       taxonomy = ["HTML", "RSS", "ATOM"] # default = ["HTML", "RSS"]
     #+end_src

* Selectively excluding pages from the feed
For the pages that you would like to exclude from the feed, set the
~disable_feed~ parameter in its front-matter to ~true~.

#+begin_src toml
disable_feed = true
#+end_src

* Change file name of the feed
You might want to change the file name or the file extension in particular from ~.xml~ to ~.atom~ to comply with [[https://filext.com/file-extension/ATOM][defined web standards]] and MIME types. It could also help for your web server to deliver the file using the correct MIME type, especially when you are not able to adjust the Content-Type HTTP header for a specific file name or directory path.

To adjust the feed's file name, you need to put the following lines to the site's ~config.toml~:

#+begin_src toml
[mediaTypes."application/atom+xml"]
  suffixes = ["atom"]
[outputFormats.Atom]
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "feed" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = feed.atom
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false
#+end_src

This will rename the feed file name from ~atom.xml~ to ~feed.atom~.
